name: bitcoindart
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 1.0.0
homepage: https://github.com/tionx3na/crypto_flutter
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bech32: ^0.2.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  pointycastle: ^3.5.2
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.7.0
  
dev_dependencies:
  test: ^1.20.2
  pedantic: ^1.11.1
